project:
  type: website

website:
  title: "Noel's Learning Journey in Visual Analytics"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1 ggplot2 Methods
            href: hands_on_ex/hands_on_ex01/hands_on_ex01.html
            
          - text: Hands-on Exercise 2
            #href: 
            
          - text: Hands-on Exercise 3
            #href: 
            
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: in_class_ex/in_class_ex01/in_class_ex01.html
            
          - text: In-class Exercise 2
            #href: 
            
          - text: In-class Exercise 3
            #href: 
            
          - text: In-class Exercise 4
            #href: 
            
          - text: In-class Exercise 5
            #href: 
            
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: take_home_ex/take_home_ex01/take_home_ex01.html
            
          - text: Take-home Exercise 2
            #href: 
            
          - text: Take-home Exercise 3
            #href: 
            
          - text: Take-home Exercise 4
            #href: 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

