project:
  type: website

website:
  title: "Noel's Learning Journey in Visual Analytics"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Exercise 1 ggplot2 Methods
            href: hands_on_ex/hands_on_ex01/hands_on_ex01.html
            
          - text: Exercise 2 ggplot2 Customisation
            href: hands_on_ex/hands_on_ex02/hands_on_ex02.html
            
          - text: Exercise 3.1 Interactive Visualisations
            href: hands_on_ex/hands_on_ex03/hands_on_ex03.html
            
          - text: Exercise 3.2 Animated Visualisations
            href: hands_on_ex/hands_on_ex03/hands_on_ex03_2.html
            
          - text: Exercise 4.1 Visualising Distributions
            href: hands_on_ex/hands_on_ex04/hands_on_ex04.html

          - text: Exercise 4.2 Visual Statistical Analysis
            href: hands_on_ex/hands_on_ex04/hands_on_ex04_2.html

          - text: Exercise 4.3 Visualising Uncertainty
            href: hands_on_ex/hands_on_ex04/hands_on_ex04_3.html
            
          - text: Exercise 4.4 Funnel Plots
            href: hands_on_ex/hands_on_ex04/hands_on_ex04_4.html
            
          - text: Exercise 5.1 Ternary Plot
            href: hands_on_ex/hands_on_ex05/hands_on_ex05.html
            
          - text: Exercise 5.2 Visual Correlation Analysis
            href: hands_on_ex/hands_on_ex05/hands_on_ex05_2.html
                        
          - text: Exercise 5.3 Heatmap
            href: hands_on_ex/hands_on_ex05/hands_on_ex05_3.html
                        
          - text: Exercise 5.4 Parellel Coordinates Plot
            href: hands_on_ex/hands_on_ex05/hands_on_ex05_4.html
                        
          - text: Exercise 5.5 Treemap Visalisation
            href: hands_on_ex/hands_on_ex05/hands_on_ex05_5.html
            
          - text: Exercise 6 Time-Oriented Data
            href: hands_on_ex/hands_on_ex06/hands_on_ex06.html  
            
          - text: Exercise 7.1 Choropleth Mapping
            href: hands_on_ex/hands_on_ex07/hands_on_ex07.html
                        
          - text: Exercise 7.2 Geospatial Data Point
            href: hands_on_ex/hands_on_ex07/hands_on_ex07_2.html
                        
          - text: Exercise 7.3 Analytical Mapping
            href: hands_on_ex/hands_on_ex07/hands_on_ex07_3.html
            
          - text: Exercise 8 Network Data
            href: hands_on_ex/hands_on_ex08/hands_on_ex08.html
            
          - text: Exercise 9 Information Dashboard
            href: hands_on_ex/hands_on_ex09/hands_on_ex09.html
            
      - text: In-class Exercises
        menu: 
          - text: Exercise 1 - Intro to R
            href: in_class_ex/in_class_ex01/in_class_ex01.html
            
          - text: Exercise 3 - Visulisation on Tableau
            href: in_class_ex/in_class_ex03/in_class_ex03.html
            
          - text: Exercise 6 - Time Series Visualisation on Tableau and R
            href: in_class_ex/in_class_ex06/in_class_ex06.html
            
          - text: Exercise 7
            href: in_class_ex/in_class_ex07/in_class_ex07.html
            
          - text: Exercise 8
            href: in_class_ex/in_class_ex08/in_class_ex08.html
            
          - text: Exercise 9
            href: in_class_ex/in_class_ex09/in_class_ex09.html
            
          - text: Exercise 10
            href: in_class_ex/in_class_ex10/in_class_ex10.html
            
      - text: Take-home Exercises
        menu: 
          - text: Exercise 1
            href: take_home_ex/take_home_ex01/take_home_ex01.html
            
          - text: Exercise 2
            href: take_home_ex/take_home_ex02/take_home_ex02.html
            
          - text: Exercise 3
            href: take_home_ex/take_home_ex03/take_home_ex03.html
            
          - text: Exercise 4
            href: take_home_ex/take_home_ex04/take_home_ex04.html
            
      - text: Shiny App
        menu: 
          - text: In-Class Exercise            
            href: https://noelnomel.shinyapps.io/prototype1/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

